### ISSUE TITLE
Guidance on adding console commands

### ISSUE THREAD

**Issue by iamkeir** [lindseydiloreto/craft-businesslogic#3]
Hello :) thank you **so much** for this plugin. For someone quite new to the Craft environment, this really helped kickstart my module/plugin development!

I was wondering - I would like to add a console controller to my businesslogic code but not 100% sure how to. I've been bouncing between your documentation and a bunch of nystudio.com articles, including their plugin factory... but not getting much luck.

Do you have any guidance at all please?

**Comment by lindseydiloreto** [comment]
That's a great idea, thanks for the suggestion @iamkeir!

I don't have any tips at this moment, but I'll make note to add console commands to the template.

**Comment by iamkeir** [comment]
@lindseydiloreto just revisiting this as we have the need again. 

Correct me if I am wrong, but I think the Businesslogic module is already able to support console commands via https://github.com/doublesecretagency/craft-businesslogic/blob/dc486a87af86491205db3716d7ffdd83b1f2354b/businesslogic/BusinessLogic.php#L40-L42

So we could run [this action](https://github.com/doublesecretagency/craft-businesslogic/blob/dc486a87af86491205db3716d7ffdd83b1f2354b/businesslogic/controllers/ExampleController.php#L111) using `./craft business-logic/example/example-route`, is that correct? Thanks!

**Comment by iamkeir** [comment]
Figured it out!

1. I needed to create a controller in `businesslogic/console/controllers`
2. I needed to add `modules\\` to the namespace override: `$this->controllerNamespace = 'modules\\businesslogic\\console\\controllers'` as BusinessLogic is namespaced as `namespace modules\businesslogic`

Might be worth adding to your README/inline comments? Or I can do a pull request!

Ref self-solved Craft issue: https://craftcms.stackexchange.com/questions/39388/how-to-run-custom-module-controller-actions-from-console/39389#39389

**Comment by lindseydiloreto** [comment]
Thanks @iamkeir! Feel free to submit a PR with that new information. 👍

**Comment by iamkeir** [comment]
@lindseydiloreto done! https://github.com/doublesecretagency/craft-businesslogic/pull/5

**Comment by lindseydiloreto** [comment]
I've just merged your PR, sorry for the delay. Thanks for your contribution @iamkeir! 🍺
