### ISSUE TITLE
Correct URL for invoking ExampleController action

### ISSUE THREAD

**Issue by dan-madoni-xc** [lindseydiloreto/craft-businesslogic#4]
Thank you for providing this module example. Once it is set up as instructed, is the following URL correct for invoking the actionExampleRoute() action in ExampleController?...

http://my-craft-site/business-logic/example/example-route

When I try it in a browser, I get a 404/Template not found: business-logic/example/example-route error rather than executing code in that action. I'm not sure if I set it up incorrectly or if I'm not understanding how to compose a URL that invokes that action as expected.

Same question posted on Craft Stack Exchange here: https://craftcms.stackexchange.com/questions/37310/what-is-the-correct-way-to-format-a-module-controller-action-url

Thank you in advance for your assistance.

**Comment by dan-madoni-xc** [comment]
I found out the cause of the issue: the ExampleController.php example specifies this namespace...

namespace modules\businesslogic\controllers;

...but BusinessLogic.php sets the controllerNameSpace like this...

```
// Adjust controller namespace for console requests
if (Craft::$app->getRequest()->getIsConsoleRequest()) {
    $this->controllerNamespace = 'businesslogic\\console\\controllers';
}
```

...it worked for me after I changed it to match the ExampleController namespace, (note the addition of **modules\\**)...

```
// Adjust controller namespace for console requests
if (Craft::$app->getRequest()->getIsConsoleRequest()) {
    $this->controllerNamespace = 'modules\\businesslogic\\console\\controllers';
} else {
    $this->controllerNamespace = 'modules\\businesslogic\\controllers';
}
```

I hope this is helpful in case anyone else runs into this issue with the example.

**Comment by lindseydiloreto** [comment]
That's interesting, thanks for the tip @dan-madoni-xc! 👍 

Those particular lines of code have gone through [some](https://github.com/doublesecretagency/craft-businesslogic/pull/2/commits/af67643c2869ea06c7f3ba81f0b682502a0375b4) [changes](https://github.com/doublesecretagency/craft-businesslogic/commit/09952504f0b684e7137c09766bea90ca40d2e90a#diff-b2a3468a7e8342c02597e589f55efcf8660a2c876ad1a341d5b8334d7a2e7832), and I'm still not 100% certain what the correct answer is. I was fairly confident about the current version, though.

May I ask, how are your modules being loaded in `composer.json`? Does it look like this?

```js
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  }
```

Also, what is your folder architecture? Does it look like this?

<img width="360" alt="modules@2x" src="https://user-images.githubusercontent.com/5309692/109890158-a8181f80-7c3b-11eb-86c7-fe5def8f9d30.png">

**Comment by lindseydiloreto** [comment]
Ah, it looks like someone has already provided an answer on Stack Exchange!

 - https://craftcms.stackexchange.com/a/37320/45

Were you able to fix it by adjusting the `config/app.php` file?

**Comment by dan-madoni-xc** [comment]
Thank you for your replies. The cause of the issue for me turned out to be the controllerNamespace reference in the controller example: ExampleController.php controller specifies this namespace...

```
namespace modules\businesslogic\controllers;
```
...but BusinessLogic.php sets the controllerNameSpace like this, (note that it's missing **modules\\**)...

```
// Adjust controller namespace for console requests
if (Craft::$app->getRequest()->getIsConsoleRequest()) {
    $this->controllerNamespace = 'businesslogic\\console\\controllers';
}
```
...it worked for me after I changed it to match the ExampleController namespace, (note the addition of **modules\\** as well as handling both console and web requests, which I added based on another example I found)...

```
// Adjust controller namespace for console requests
if (Craft::$app->getRequest()->getIsConsoleRequest()) {
    $this->controllerNamespace = 'modules\\businesslogic\\console\\controllers';
} else {
    $this->controllerNamespace = 'modules\\businesslogic\\controllers';
}
```
I'm not sure if I'm doing something else incorrectly or if the above change needs to be made to your example, but it's working nicely for me now.

Thank you for providing the BusinessLogic example in the first place, it has been very helpful!

**Comment by lindseydiloreto** [comment]
Ok awesome, glad you got it sorted out! 👍
