### ISSUE TITLE
Calling a service from variables

### ISSUE THREAD

**Issue by jasonmckinney66** [lindseydiloreto/craft-businesslogic#7]
First of all, thanks so much for putting this together. It's been a great help.
Quick question for you:
In your [support page for variables](https://doublesecretagency.github.io/craft-businesslogic/variables), you list the following example for calling a service from variables (modified for the actual businesslogic module):
```
public function exampleService()
    {
        return BusinessLogic::$instance->example->exampleService();
    }
```
This is returning the error: **Class "modules\businesslogic\variables\BusinessLogic" not found**
Can you tell me if there's something obvious I'm missing here? Is this potentially Craft 4 related? Thanks in advance.

**Comment by lindseydiloreto** [comment]
Great, glad it's been helpful for you! 👍 

Sounds like you're having a namespace issue. Try adding something like this to the top of the file...

```php
use modules\businesslogic\BusinessLogic;
```

This will tell the PHP file where to find the `BusinessLogic` class.

---

For the record, this Business Logic example module is probably going away soon. It's largely been made obsolete by the official [plugin/module generator](https://craftquest.io/articles/generate-craft-cms-plugin-and-module-code). I'd recommend doing some further exploration with that tool. 🙂
